### ISSUE TITLE
How to fix this error?

### ISSUE THREAD

**Issue by yothin** [antongorodezkiy/codeigniter-apns#5]
I can send push notification work correctly but i got this error

Severity: Warning

Message: stream_select() [function.stream-select]: You MUST recompile PHP with a larger value of FD_SETSIZE. It is set to 1024, but you have descriptors numbered at least as high as 4511. --enable-fd-setsize=5120 is recommended, but you may want to set it to equal the maximum number of open files supported by your system, in order to avoid seeing this error again at a later date.

Filename: libraries/apn.php

Line Number: 396

**Comment by antongorodezkiy** [comment]
Hello @yothin 
This is not a codeigniter-apns library issue as far as I can understand. Something is wrong with PHP installation, so PHP is asking to recompile it. And seems this is not a PHP bug also, please check this old thread for more information https://bugs.php.net/bug.php?id=37025&edit=1
